Traceback (most recent call last):
  File "/home/ziygawish/CURIS-workplace/reverse.py", line 18, in <module>
    main()
  File "/home/ziygawish/CURIS-workplace/reverse.py", line 13, in main
    filename = sys.argv[2]
IndexError: list index out of range
